#!/bin/bash -eu

# move to project root
cd "$(readlink -f $(dirname $0)/..)"

temp=$(mktemp -d)
trap "rm -rf \"${temp}\"" EXIT

wget 'https://github.com/FluffyStuff/riichi-mahjong-tiles/archive/master.zip' -O "${temp}/master.zip"
unzip "${temp}/master.zip" -d "${temp}/"

src_dir="${temp}/riichi-mahjong-tiles-master/Regular"
dst_dir='./static/image/paiga'

rm -rf "${dst_dir}"/*.svg

names=(
    'Man5-Dora:5\$m'
    'Pin5-Dora:5\$p'
    'Sou5-Dora:5\$s'
    'Ton:1j'
    'Nan:2j'
    'Shaa:3j'
    'Pei:4j'
    'Haku:5j'
    'Hatsu:6j'
    'Chun:7j'
    'Back:_'
)

for cat in Man:m Pin:p Sou:s; do
    IFS=: read src_cat dst_cat <<< "${cat}"
    for n in $(seq 1 9); do
        names+=("${src_cat}${n}:${n}${dst_cat}")
    done
done

for pair in "${names[@]}"; do
    IFS=: read src_name dst_name <<< "${pair}"
    cp -v "${src_dir}/${src_name}.svg" "${dst_dir}/${dst_name}.svg"
done
